apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Pod
metadata:
  name: rsync-damo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /rbd
      name: ceph-rbd
    - mountPath: /cephfs
      name: nfs
  volumes:
  - name: ceph-rbd
    persistentVolumeClaim:
      claimName: ceph-rbd-pvc
  - name: nfs
    flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      options:
        clusterNamespace: rook-ceph
        fsName: myfs
