name: Auto Create PR

on:
  push:
    branches: 
      - 'lixie'  # 仅监听 lixie 分支

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史

      - name: Auto Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto PR from ${{ github.ref_name }}"
          body: "Automated PR created from ${{ github.ref_name }} branch."
          base: master      # PR 目标分支
          branch: "auto-pr/${{ github.ref_name }}"  # 临时分支名
          delete-branch: true  # 合并后删除临时分支
          draft: false
          labels: "auto-pr"
          commit-message: "Auto PR from ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
