name: Auto Create PR

on:
  push:
    branches-ignore:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auto Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto PR from ${{ github.ref_name }}"
          body: "Automated PR created from ${{ github.ref_name }} branch."
          base: master
          branch: "auto-pr/${{ github.ref_name }}"
          delete-branch: true
          draft: false
          labels: "auto-pr"
          commit-message: "Auto PR from ${{ github.ref_name }}"
          debug: true  # 启用调试模式
