name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # 你可以指定任何分支来触发构建
      - master
  pull_request:
    branches:
      - main   # 也可以在 PR 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 获取代码
      
    - name: Extract tag info
      id: vars
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        DATE_TAG=$(date +%Y%m%d)
        echo "TAG=${DATE_TAG}-${SHORT_SHA}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # 设置 Docker 构建环境

    - name: Log in to Alibaba Cloud Registry
      run: |
        docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} ${{
        secrets.ALIYUN_REGISTRY }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/mkdocs_blog:${{ steps.vars.outputs.TAG }} .  # 使用 git commit hash 作为 tag 名

    - name: Push Docker image to Alibaba Cloud
      run: |
        docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/mkdocs_blog:${{ steps.vars.outputs.TAG }}  # 推送镜像到阿里云仓库

